"""Initial schema

Revision ID: 0bdc92abbcad
Revises: 
Create Date: 2025-10-30 18:11:07.473194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdc92abbcad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('azure_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_owner_status', 'projects', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('servers_count', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_project_date', 'file_uploads', ['project_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    op.create_table('landing_zone_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('migrate_project_name', sa.String(length=255), nullable=False),
    sa.Column('migrate_project_rg', sa.String(length=255), nullable=False),
    sa.Column('recovery_vault_name', sa.String(length=255), nullable=False),
    sa.Column('recovery_vault_rg', sa.String(length=255), nullable=False),
    sa.Column('cache_storage_account', sa.String(length=255), nullable=False),
    sa.Column('cache_storage_rg', sa.String(length=255), nullable=False),
    sa.Column('auto_create_storage', sa.Boolean(), nullable=True),
    sa.Column('appliance_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_one_lz_per_project')
    )
    op.create_index('idx_lz_project', 'landing_zone_configs', ['project_id'], unique=False)
    op.create_index(op.f('ix_landing_zone_configs_id'), 'landing_zone_configs', ['id'], unique=False)
    op.create_table('server_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_machine_name', sa.String(length=255), nullable=False),
    sa.Column('target_region', sa.String(length=100), nullable=False),
    sa.Column('target_subscription', sa.String(length=255), nullable=False),
    sa.Column('target_resource_group', sa.String(length=255), nullable=False),
    sa.Column('target_vnet', sa.String(length=255), nullable=False),
    sa.Column('target_subnet', sa.String(length=255), nullable=False),
    sa.Column('target_machine_sku', sa.String(length=100), nullable=False),
    sa.Column('target_disk_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'target_machine_name', name='uq_server_per_project')
    )
    op.create_index('idx_server_project_name', 'server_configs', ['project_id', 'target_machine_name'], unique=False)
    op.create_index('idx_server_region', 'server_configs', ['target_region'], unique=False)
    op.create_index(op.f('ix_server_configs_id'), 'server_configs', ['id'], unique=False)
    op.create_table('validation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='validationstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=True),
    sa.Column('passed_items', sa.Integer(), nullable=True),
    sa.Column('warning_items', sa.Integer(), nullable=True),
    sa.Column('failed_items', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index('idx_job_celery_task', 'validation_jobs', ['celery_task_id'], unique=False)
    op.create_index('idx_job_project_status', 'validation_jobs', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_validation_jobs_id'), 'validation_jobs', ['id'], unique=False)
    op.create_table('lz_validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('validation_job_id', sa.Integer(), nullable=True),
    sa.Column('validation_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'WARNING', 'FAILED', 'SKIPPED', name='validationresultstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['landing_zone_configs.id'], ),
    sa.ForeignKeyConstraint(['validation_job_id'], ['validation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lz_validation_config', 'lz_validation_results', ['config_id'], unique=False)
    op.create_index('idx_lz_validation_job', 'lz_validation_results', ['validation_job_id'], unique=False)
    op.create_index('idx_lz_validation_type_status', 'lz_validation_results', ['validation_type', 'status'], unique=False)
    op.create_index(op.f('ix_lz_validation_results_id'), 'lz_validation_results', ['id'], unique=False)
    op.create_table('replication_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('NOT_STARTED', 'INITIALIZING', 'REPLICATING', 'PROTECTED', 'FAILED', 'DISABLED', name='replicationstate'), nullable=False),
    sa.Column('health', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', 'UNKNOWN', name='replicationhealth'), nullable=False),
    sa.Column('vault_name', sa.String(length=255), nullable=True),
    sa.Column('protected_item_id', sa.String(length=500), nullable=True),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rpo_minutes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('replication_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    op.create_index('idx_replication_state_health', 'replication_status', ['state', 'health'], unique=False)
    op.create_index('idx_replication_vault', 'replication_status', ['vault_name'], unique=False)
    op.create_index(op.f('ix_replication_status_id'), 'replication_status', ['id'], unique=False)
    op.create_table('server_validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('validation_job_id', sa.Integer(), nullable=True),
    sa.Column('validation_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'WARNING', 'FAILED', 'SKIPPED', name='validationresultstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_configs.id'], ),
    sa.ForeignKeyConstraint(['validation_job_id'], ['validation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_validation_job', 'server_validation_results', ['validation_job_id'], unique=False)
    op.create_index('idx_server_validation_server', 'server_validation_results', ['server_id'], unique=False)
    op.create_index('idx_server_validation_type_status', 'server_validation_results', ['validation_type', 'status'], unique=False)
    op.create_index(op.f('ix_server_validation_results_id'), 'server_validation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_validation_results_id'), table_name='server_validation_results')
    op.drop_index('idx_server_validation_type_status', table_name='server_validation_results')
    op.drop_index('idx_server_validation_server', table_name='server_validation_results')
    op.drop_index('idx_server_validation_job', table_name='server_validation_results')
    op.drop_table('server_validation_results')
    op.drop_index(op.f('ix_replication_status_id'), table_name='replication_status')
    op.drop_index('idx_replication_vault', table_name='replication_status')
    op.drop_index('idx_replication_state_health', table_name='replication_status')
    op.drop_table('replication_status')
    op.drop_index(op.f('ix_lz_validation_results_id'), table_name='lz_validation_results')
    op.drop_index('idx_lz_validation_type_status', table_name='lz_validation_results')
    op.drop_index('idx_lz_validation_job', table_name='lz_validation_results')
    op.drop_index('idx_lz_validation_config', table_name='lz_validation_results')
    op.drop_table('lz_validation_results')
    op.drop_index(op.f('ix_validation_jobs_id'), table_name='validation_jobs')
    op.drop_index('idx_job_project_status', table_name='validation_jobs')
    op.drop_index('idx_job_celery_task', table_name='validation_jobs')
    op.drop_table('validation_jobs')
    op.drop_index(op.f('ix_server_configs_id'), table_name='server_configs')
    op.drop_index('idx_server_region', table_name='server_configs')
    op.drop_index('idx_server_project_name', table_name='server_configs')
    op.drop_table('server_configs')
    op.drop_index(op.f('ix_landing_zone_configs_id'), table_name='landing_zone_configs')
    op.drop_index('idx_lz_project', table_name='landing_zone_configs')
    op.drop_table('landing_zone_configs')
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_index('idx_upload_project_date', table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index('idx_project_owner_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
