"""add_migrate_project_fields_to_servers

Revision ID: 9d31797894b9
Revises: make_config_id_nullable
Create Date: 2025-11-04 08:58:48.205425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d31797894b9'
down_revision: Union[str, None] = 'make_config_id_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to server_configs table
    op.add_column('server_configs', sa.Column('migrate_project_name', sa.String(length=255), nullable=True))
    op.add_column('server_configs', sa.Column('appliance_name', sa.String(length=255), nullable=True))
    op.add_column('server_configs', sa.Column('appliance_type', sa.String(length=50), nullable=True))
    op.add_column('server_configs', sa.Column('recovery_vault_name', sa.String(length=255), nullable=True))
    op.create_index('idx_server_migrate_project', 'server_configs', ['migrate_project_name'], unique=False)
    op.create_index(op.f('ix_server_configs_migrate_project_name'), 'server_configs', ['migrate_project_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_configs_migrate_project_name'), table_name='server_configs')
    op.drop_index('idx_server_migrate_project', table_name='server_configs')
    op.drop_column('server_configs', 'recovery_vault_name')
    op.drop_column('server_configs', 'appliance_type')
    op.drop_column('server_configs', 'appliance_name')
    op.drop_column('server_configs', 'migrate_project_name')
    # ### end Alembic commands ###
