"""Add Azure authentication fields to projects

Revision ID: 810f3c6c1811
Revises: 0bdc92abbcad
Create Date: 2025-11-03 13:07:29.625015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810f3c6c1811'
down_revision: Union[str, None] = '0bdc92abbcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('azure_tenant_id', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('auth_method', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('auth_credentials', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('auth_token', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('auth_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'auth_token_expires_at')
    op.drop_column('projects', 'auth_token')
    op.drop_column('projects', 'auth_credentials')
    op.drop_column('projects', 'auth_method')
    op.drop_column('projects', 'azure_tenant_id')
    # ### end Alembic commands ###
